accounts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^confirm/(?P<token>[a-z0-z\-]+)/$', views.confirm, name='confirm'),
]

record/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accept/$', views.match_accept, name='match_accept'),
    url(r'^cancel/$', views.match_cancel, name='match_cancel'),
    url(r'^detail/(?P<pk1>\d+)/(?P<pk2>\d+)/$', views.detail, name='detail'),
    url(r'^find/(?P<mode>\w+)/$', views.find, name='find'),
    url(r'^new/$', views.match_new, name='match_new'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^reject/$', views.match_reject, name='match_reject'),
    url(r'^resend/$', views.match_resend, name='match_resend'),
    url(r'^show/$', views.match_show, name='match_show'),
]

winning/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('record.urls', namespace='record')),
]

record/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Team(models.Model):
    teamname = models.CharField(max_length=20)

    class Meta:
        ordering = ['teamname']

    def __str__(self):
        return self.teamname

class Match(models.Model):
    player1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='player1')
    player2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='player2')
    team1 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team1')
    team2 = models.ForeignKey(Team, on_delete=models.CASCADE, related_name='team2')
    time = models.DateTimeField(auto_now_add=True)
    score1 = models.IntegerField()
    score2 = models.IntegerField()
    accept1 = models.BooleanField()
    accept2 = models.BooleanField()
    reject = models.BooleanField()

    def __str__(self):
        return self.player1.username+' '+self.player2.username+' ('+str(self.time)+')'

class Rival(models.Model):
    player = models.ForeignKey(User)

record/forms.py
from django.forms import ModelForm

from .models import Match, Rival


class MatchForm(ModelForm):
    class Meta:
        # Meta class describes "anything that's not a field".
        model = Match
        exclude = ['player1', 'player2', 'time', 'accept1', 'accept2', 'reject']


class RivalForm(ModelForm):
    class Meta:
        model = Rival
        fields = '__all__'

record/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect, render

# from accounts.forms import MyUserCreationForm as UserCreationForm
from accounts.forms import MyUserCreationForm as UserCreationForm
from accounts.forms import MyAuthenticationForm as AuthenticationForm

from .forms import MatchForm
from .models import Match, Team
from .utils import getkey


# Create your views here.
def index(request):
    try:
        Q1 = Q(player1=request.user, accept1=False, accept2=True)
        Q2 = Q(player2=request.user, accept1=True, accept2=False)
        matches_to_me = Match.objects.filter(Q1 | Q2)
        matches_to_me = matches_to_me.filter(reject=False).order_by('time')
        num = len(matches_to_me)
    except:
        num = 0

    if request.user.is_authenticated():
        name = request.user.profile.name
        return render(request, 'record/index.html', {
            'num': num,
            'name': name,
        })
    else:
        signup_form = UserCreationForm()
        login_form = AuthenticationForm()
        return render(request, 'record/index.html', {
            'signup_form': signup_form,
            'login_form': login_form,
        })


@login_required
def profile(request):
    # 내가 player1이고 accept2가 False 혹은 내가 player2이고 accept1이 False
    Q1_by_me = Q(player1=request.user, accept1=True, accept2=False)
    Q2_by_me = Q(player2=request.user, accept1=False, accept2=True)
    matches_by_me = Match.objects.filter(Q1_by_me | Q2_by_me)
    matches_by_me = matches_by_me.filter(reject=False).order_by('time')
    # 내가 player1이고 accept1이 False 혹은 내가 player2이고 accept2가 False
    Q1_to_me = Q(player1=request.user, accept1=False, accept2=True)
    Q2_to_me = Q(player2=request.user, accept1=True, accept2=False)
    matches_to_me = Match.objects.filter(Q1_to_me | Q2_to_me)
    matches_to_me = matches_to_me.filter(reject=False).order_by('time')
    # 내가 player1 혹은 player2이고 accept은 둘 다 False
    Q1_rejected = Q(player1=request.user, accept1=True, accept2=False)
    Q2_rejected = Q(player2=request.user, accept1=False, accept2=True)
    matches_rejected = Match.objects.filter(Q1_rejected | Q2_rejected)
    matches_rejected = matches_rejected.filter(reject=True).order_by('time')

    return render(request, "record/profile.html", {
        "matches_by_me": matches_by_me,
        "matches_to_me": matches_to_me,
        "matches_rejected": matches_rejected,
    })


@login_required
def match_cancel(request):
    if request.method == 'POST':
        model = Match.objects.get(pk=request.POST['pk'])
        model.delete()
        return redirect('record:profile')


@login_required
def match_accept(request):
    if request.method == 'POST':
        model = Match.objects.get(pk=request.POST['pk'])
        model.accept1, model.accept2 = True, True
        model.save()
        return redirect('record:profile')


@login_required
def match_reject(request):
    if request.method == 'POST':
        model = Match.objects.get(pk=request.POST['pk'])
        model.reject = True
        model.save()
        return redirect('record:profile')


@login_required
def match_resend(request):
    if request.method == 'POST':
        model = Match.objects.get(pk=request.POST['pk'])
        model.reject = False
        model.save()
        return redirect('record:profile')


@login_required
def match_show(request):
    if request.method == 'POST':
        form = MatchForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            match_id = "match-"+request.POST['id']
            return render(request, 'record/match_show.html', {
                "model": model,
                "match_id": match_id,
            })
    else:
        pass


@login_required
def match_new(request):
    # request.method 로 분기한다.
    if request.method == 'POST':
        form = MatchForm(request.POST)
        if form.is_valid():
            form = MatchForm(request.POST)
            if form.is_valid():
                model = form.save(commit=False)
                # 전적 생성 직후에 reject 값은 False 이다.
                model.reject = False
                player1 = request.user
                player2 = User.objects.get(pk=int(request.GET['rival']))

                # model에 player를 입력할때는 pk가 작은게 player1, pk가 큰게 player2로 넣는다.
                if player1.pk < player2.pk:
                    model.player1, model.player2 = player1, player2
                    model.accept1, model.accept2 = True, False
                else:
                    # 점수, 팀, 스코어를 뒤집어서 넣어준다.
                    model.player1, model.player2 = player2, player1
                    model.team1, model.team2 = model.team2, model.team1
                    model.score1, model.score2 = model.score2, model.score1
                    model.accept1, model.accept2 = False, True

                model.save()
                response_data = {}
                response_data['pk'] = model.pk

            return JsonResponse(response_data)
    else:
        form = MatchForm()
        # teams = Team.objects.all().order_by('teamname')

    return render(request, 'record/match_new.html', {
        'form': form,
        # 'teams': teams,
    })


@login_required
def find(request, mode):
    if request.is_ajax():
        # username을 받아온뒤 존재하는지 확인한다.
        username = request.POST['username']
        try:
            rival = User.objects.get(username=username)
        except:
            rival = None
        if mode == "new":
            button_text = "전적 추가하러 가기"
        elif mode == "detail":
            button_text = "전적 확인하러 가기"
        return render(request, 'record/findresult.html', {
            'rival': rival,
            'button_text': button_text,
        })

    elif request.method == 'POST':
        pk1 = request.user.pk
        pk2 = int(request.POST['id'])
        # 전적 생성이 요청된 경우.
        if mode == "new":
            url = reverse('record:match_new')
            url = url + '?rival=' + str(pk2)
            return redirect(url)
        # 전적 확인이 요청된 경우.
        elif mode == "detail":
            return redirect('record:detail', pk1, pk2)
    else:
        if mode == "new":
            title_text = "함께 플레이한 유저를 검색해주세요."
        elif mode == "detail":
            title_text = "전적이 궁금한 유저를 입력해주세요."
        return render(request, 'record/rival.html', {
            'title_text': title_text,
        })


@login_required
def detail(request, pk1, pk2):
    if request.user.pk == int(pk1):
        p1, p2 = User.objects.get(pk=pk1), User.objects.get(pk=pk2)

        # pk 값이 작은쪽이 늘 player1으로 만들어져있을 것이다.
        matches = Match.objects.filter(accept1=True, accept2=True)
        if pk1 < pk2:
            matches = matches.filter(player1=p1, player2=p2).order_by('-time')

        else:
            matches = matches.filter(player1=p2, player2=p1).order_by('-time')

        win, draw, defeat, GF, GA = 0, 0, 0, 0, 0
        for match in matches:
            GF = GF + match.score1
            GA = GA + match.score2
            if match.score1 > match.score2:
                win = win + 1
            elif match.score1 < match.score2:
                defeat = defeat + 1
            else:
                draw = draw + 1
        # pk1이 더 크다면, 뒤집어줄 것을 뒤집어준다.
        if pk1 > pk2:
            win, defeat, GF, GA = defeat, win, GA, GF

        last_five = matches[:5]
        curr_five = ""
        if pk1 < pk2:
            for match in last_five:
                if match.score1 > match.score2:
                    curr_five = '승' + curr_five
                elif match.score1 < match.score2:
                    curr_five = '패' + curr_five
                else:
                    curr_five = '무' + curr_five
        else:
            for match in last_five:
                if match.score1 > match.score2:
                    curr_five = '패' + curr_five
                elif match.score1 < match.score2:
                    curr_five = '승' + curr_five
                else:
                    curr_five = '무' + curr_five

        if pk1 < pk2:
            Q_1s = Q(player1=p1, player2=p2)
            team1s = Match.objects.filter(Q_1s).values('team1').distinct()
            infos = []
            for team1 in team1s:
                team = Team.objects.get(pk=team1['team1'])
                matches = Match.objects.filter(Q_1s).filter(team1=team)
                if len(matches) >= 3:
                    twin, tdraw, tdefeat = 0, 0, 0
                    for m in matches:
                        twin = twin + (m.score1 > m.score2)
                        tdraw = tdraw + (m.score1 == m.score2)
                        tdefeat = tdefeat + (m.score1 < m.score2)
                    point = (twin * 3 + tdraw) / len(matches)
                    infos.append({"teamname": team.teamname, "point": point})
            # point 내림차순으로 정렬.
            infos.sort(key=getkey, reverse=True)
        else:
            Q_2s = Q(player1=p2, player2=p1)
            team2s = Match.objects.filter(Q_2s).values('team2').distinct()
            infos = []
            for team2 in team2s:
                team = Team.objects.get(pk=team2['team2'])
                matches = Match.objects.filter(Q_2s).filter(team2=team)
                if len(matches) >= 3:
                    twin, tdraw, tdefeat = 0, 0, 0
                    for m in matches:
                        twin = twin + (m.score1 < m.score2)
                        tdraw = tdraw + (m.score1 == m.score2)
                        tdefeat = tdefeat + (m.score1 > m.score2)
                    point = (twin * 3 + tdraw) / len(matches)
                    infos.append({"teamname": team.teamname, "point": point})
            # point 내림차순으로 정렬.
            infos.sort(key=getkey, reverse=True)

        return render(request, 'record/detail.html', {
            'p1': p1,
            'p2': p2,

record/templates/record/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {
                margin: 0;
                overflow: auto;
            }
            form {
                margin: 0;
            }
            input, button {
                width: 70vw;
                height: 5vh;
            }
            input {
                font-size: 3vh;
                margin: auto;
            }
            button {
                margin-left: 15vw;
                margin-right: 15vw;
                font-size: 2.5vh;
            }
            p {
                text-align: center;
            }
            .header {
                width: 100vw;
                height: 10vh;
                background-color: black;
            }
            .header > .home-text, .menu-text {
                display: inline-block;
                width: 30vw;
                font-size: 4vh;
                margin: 0;
                color: white;
                /*background-color: red;*/
            }
            .header > .title-text {
                display: inline-block;
                width: 40vw;
                font-size: 4vh;
                margin: 0;
                color: white;
                /*background-color: blue;*/
            }
            .header > .home-text {
                float: left;
            }
            .header > .menu-text {
                float: right;
            }
            .dropdown-content {
                display: none;
            }
            .dropdown-content > p {
                width: 100vw;
                height: 5vh;
                margin: 0;
                font-size: 3vh;
                border-style: solid;
                border-color: gray;
                /*display: block;*/
                /*background-color: black;*/
            }
            .show {
                display: block;
            }
            .main {
                width: 100vw;
                margin-top: 10vh;
                margin-bottom: 10vh;
            }
            .footer {
                width: 100vw;
                height: 10vh;
                background-color: gray;
                color: white;
                font-size: 1.5vh;
                overflow: auto;
            }
            .footer > p {
                margin-top: 1vh;
                margin-bottom: 0;
                margin-left: 3vw;
                color: white;
                font-size: 2.2vh;
            }
        </style>
        {% block style %}
        {% endblock %}
    </head>
    <body>
        <div class="header">
            <p class="home-text"><a style="text-decoration: none; color: white;" href="{% url "record:index" %}">HOME</a></p>
            <p class="title-text">
                {% block title %}
                {% endblock %}
            </p>
            {# <p style="color: white;">로그인</p> #}
            <p class="menu-text"><a onclick="myToggle()">MENU</a></p>
        </div>
        <div id="myDropdown" class="dropdown-content">
            <p><a>Link 1</a></p>
            <p><a>Link 2</a></p>
            <p><a>Link 3</a></p>
        </div>
        <div class="main">
            {% block main %}
            {% endblock %}
        </div>
        <div class="footer">
            <p style="font-weight: bold;">Python 웹 프레임워크 Django로 만들어졌습니다.</p>
            <p>special thanks to <em>allieuslee</em> (a.k.a <em>Ask Django</em>)</p>
        </div>
        <script src="{% static "jquery-3.0.0.min.js" %}"></script>
        <script src="{% static "jquery.csrf.js" %}"></script>
        <script>
            function myToggle() {
                document.getElementById("myDropdown").classList.toggle("show");
            }
        </script>
        {% block script %}
        {% endblock %}
    </body>
</html>

record/templates/record/detail.html
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<p><B>{{ p1.profile.nickname }}</B>님의 <B>{{ p2.profile.nickname }}</B>님에 대한 상대전적 입니다. </p>
<hr/>
<p><B>통산 전적</B></p>
<p>{{ win }}승 {{ draw }}무 {{ defeat }}패</p>
<p><B>통산 득/실점</B></p>
<p>{{ GF }}득점 {{ GA }}실점</p>
<p><B>최근 5경기 전적</B> ({{ curr_five }})</p>
{% for match in last_five %}
    {% if pk1_is_smaller %}
        <p>{{ match.team1 }} <B>{{ match.score1 }}</B> vs <B>{{ match.score2 }}</B> {{ match.team2 }}</p>
    {% else %}
        <p>{{ match.team2 }} <B>{{ match.score2 }}</B> vs <B>{{ match.score1 }}</B> {{ match.team1 }}</p>
    {% endif %}
{% endfor %}
<p><B>경기당 평균 승점 상위 3팀(3경기 이상 진행 팀 한정)</B></p>
{% for info in infos %}
    <p>{{info.teamname}}: {{info.point}}</p>
{% endfor %}
<hr/>
<p><a href="{% url 'record:index' %}">메인 페이지로</a></p>

record/templates/record/index.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <!-- Viewport Setting -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Semantic UI Core CSS -->
    {# <link href="{% static "semantic.min.css" %}" rel="stylesheet"> #}
    {# <link href="{% static "icon.min.css" %}" rel="stylesheet"> #}
    <!-- Style Tag for image -->
    <style>
        body, html{
            width: 100%;
            /*height: 100%;*/
            margin: 0px;
            overflow: auto;
        }
        body {
            background-color: black;
            /*padding-top: 10%;*/
        }
        .main-alarm {
            text-align: center;
            color: white;
            font-size: 2vh;
        }
        .main-alarm > a {
            color: white;
            text-decoration: underline;
        }
        .main-title {
            width: 90%;
            margin-left: 5vw;
            margin-right: 5vw;
            margin-top: 15vh;
            margin-bottom: 0vh;
            text-align: center;
            color: white;
            font-size: 20vw;
            font-weight: bold;
        }
        .main-content {
            width: 80%;
            margin-left: 10vw;
            margin-right: 10vw;
            margin-top: 0vh;
            margin-bottom: 5vh;
            text-align: center;
            color: white;
            font-size: 4.5vw;
            /*text-align: center;*/
        }
        button {
            width: 60vw;
            height: 6vh;
            margin-left: 20vw;
            margin-right: 20vw;
            margin-bottom: 1.5vh;
            font-size: 4.5vw;
            border: none;
            border-radius: 1vw;
            background-color: #555555;
            color: white;
            display: none;
        }
        button.blue {
            background-color: #008CBA;
        }
        button.gray {
            background-color: #555555;
        }
        .background {
            z-index: 0;
            width: 100vw;
            height: 100vh;
            /*background-image: url({% static "main.jpg" %});*/
            /*-webkit-filter: blur(7px) grayscale(80%) opacity(100%);*/
        }
        .main {
            z-index: 1;
        }
        .main, .background {
            /*position: absolute;*/
        }
        form {
            width: 60vw;
            margin: auto;
            display: none;
        }
        input {
            /*padding: 3vw;*/
            font-size: 4.5vw;
            width: 100%;
            height: 6vh;
            border: none;
            /*border-radius: 0.5vw;*/
        }
        .show {
            display: block;
        }

        .message {
            padding: 20px;
            color: white;
            opacity: 1;
            transition: opacity 0.6s;
            margin-bottom: 15px;
        }
        .message.success {background-color: #4CAF50;}
        .message.info {background-color: #2196F3;}
        .message.warning {background-color: #ff9800;}
        .closebtn {
            margin-left: 15px;
            color: white;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }
        .closebtn:hover {
            color: black;
        }
        #form-error {
            width: 60vw;
            min-height: 6vh;
            line-height: 6vh;
            margin-left: 20vw;
            margin-right: 20vw;
            margin-bottom: 1.5vh;
            background-color: red;
            text-align: center;
            color: white;
            font-size: 3vw;
            border: none;
            border-radius: 1vw;
            display: none;
        }
    </style>
</head>
<body>
    {% comment %}
    <div class="background"></div>
    {% endcomment %}
    <div class="main">
        {% if user.is_authenticated %}
            <p class="main-title">Winning</p>
            <p class="main-content">{{user.profile.name}}님 환영합니다!</p>
            {% if num != 0 %}
            <p class="main-alarm"><a href="{% url "record:profile" %}">{{num}}</a>건의 매치가 승인 대기중입니다</p>
            {% endif %}
            <button class="gray show" onclick="location.href='{% url "logout" %}'">로그아웃</button>
            <button class="blue show" onclick="location.href='{% url "record:profile" %}'">마이 페이지</button>
            <button class="blue show" onclick="location.href='{% url "record:find" "new" %}'">전적 생성</button>
            <button class="blue show" onclick="location.href='{% url "record:find" "detail" %}'">전적 확인</button>
        {% else %}
            {% if messages %}
            {% for message in messages %}
            <div class="message {{message.tags}}">
                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            <p class="main-title">Winning</p>
            <p class="main-content">당신의 게임을 기록하세요. <br>그리고 더 많은 승리를 쟁취하세요.</p>
            <form action="{% url "accounts:signup" %}" method="POST" id="form-signup">
                {% csrf_token %}
                {{signup_form|linebreaks}}
            </form>
            <form action="{% url "accounts:login" %}" method="POST" id="form-login">
                {% csrf_token %}
                {{login_form|linebreaks}}
            </form>
            <div id="form-error"></div>
            <button class="button-signup blue show">시작하기</button>
            <button class="button-signup-submit blue">가입</button>
            <button class="button-login gray show">로그인</button>
            <button class="button-login-submit gray">로그인</button>
        {% endif %}
    </div>
    <script src="{% static "jquery-3.0.0.min.js" %}"></script>
    <script type="text/javascript">
        $(".button-signup").click(function(){
            // 자기 자신을 없앤다.
            $(this).toggleClass("show");
            // 로그인 버튼을 없앤다.
            $(".button-login").toggleClass("show");
            // 가입 버튼을 보이게 한다.
            $(".button-signup-submit").toggleClass("show");
            // Signup Form을 보이게 한다.
            $("#form-signup").slideDown("slow");
        });
        $(".button-signup-submit").click(function(){
            // $("#form-signup").submit();
            $("#form-error").slideDown();
            $("#form-error").text("계정정보를 생성중입니다...");
            $.ajax({
                // AJAX로 비동기적으로 form data를 담당 view에게 보낸다.
                url: $("#form-signup").attr("action"),
                type : "POST",
                data : $("#form-signup").serialize(),
            }).done(function(response) {
                if(response.status){
                    $(location).attr("href", response.url)
                }
                else{
                    $("#form-error").slideUp();
                    $("#form-error").text(response.error);
                    $("#form-error").slideDown();
                }
                // AJAX call이 종료된 후에 이 함수가 실행된다는 것은,
                // redirection이 이뤄지지 않은 것이므로 Form에 error가 있었다는 것이다.
                // error message를 띄워준다.
            });
        });
        $(".button-login").click(function(){
            // 자기 자신을 없앤다.
            $(this).toggleClass("show");
            // 회원가입 버튼을 없앤다.
            $(".button-signup").toggleClass("show");
            // 로그인 제출 버튼을 보이게 한다.
            $(".button-login-submit").toggleClass("show");
            // Login Form을 보이게 한다.
            $("#form-login").slideDown("slow");
        });
        $(".button-login-submit").click(function(){
            // $("#form-signup").submit();
            $("#form-error").slideUp();
            $("#form-error").text("");
            $.ajax({
                // AJAX로 비동기적으로 form data를 담당 view에게 보낸다.
                url: $("#form-login").attr("action"),
                type : "POST",
                data : $("#form-login").serialize(),
            }).done(function(response) {
                if(response.status){
                    $(location).attr("href", response.url)
                }
                else{
                    $("#form-error").text(response.error);
                    $("#form-error").slideDown();
                }
            });
        });
    </script>
</body>
</html>

record/templates/record/profile.html
{% extends "record/base.html"%}
{% load staticfiles %}

{% block title %}
    마이페이지
{% endblock %}

{% block main %}
    <p>총 <span id="num_to_me">{{matches_to_me|length}}</span>건의 매치가 {{request.user.username}}님의 승인을 기다리고 있습니다.</p>
    {% for match in matches_to_me %}
        <div id="{{match.pk}}">
        {% if match.player1.pk == request.user.pk %}
            (vs {{match.player2}}) {{match.team1}} {{match.score1}} vs {{match.score2}} {{match.team2}} {{match.time}}
        {% else %}
            (vs {{match.player1}}) {{match.team2}} {{match.score2}} vs {{match.score1}} {{match.team1}} {{match.time}}
        {% endif %}
        <span onclick="accept_match({{match.pk}})">승인 </span>
        <span onclick="reject_match({{match.pk}})">거절 </span>
        </div>
    {% endfor %}
    <hr/>
    <p>총 <span id="num_by_me">{{matches_by_me|length}}</span>건의 매치가 상대방의 승인을 기다리고 있습니다.</p>
    {% for match in matches_by_me %}
        <div id="{{match.pk}}">
        {% if match.player1.pk == request.user.pk %}
            (vs {{match.player2}}) {{match.team1}} {{match.score1}} vs {{match.score2}} {{match.team2}} {{match.time}}
        {% else %}
            (vs {{match.player1}}) {{match.team2}} {{match.score2}} vs {{match.score1}} {{match.team1}} {{match.time}}
        {% endif %}
        <span onclick="cancel_match({{match.pk}}, false)">취소</span>
        </div>
    {% endfor %}
    <p>총 <span id="num_rejected">{{matches_rejected|length}}</span>건의 매치를 상대방이 승인 거절 하였습니다.</p>
    {% for match in matches_rejected %}
        <div id="{{match.pk}}">
        {% if match.player1.pk == request.user.pk %}
            (vs {{match.player2}}) {{match.team1}} {{match.score1}} vs {{match.score2}} {{match.team2}} {{match.time}}
        {% else %}
            (vs {{match.player1}}) {{match.team2}} {{match.score2}} vs {{match.score1}} {{match.team1}} {{match.time}}
        {% endif %}
        <span onclick="cancel_match({{match.pk}}, true)">취소 </span>
        <span onclick="resend_match({{match.pk}})">재요청 </span>
        </div>
    {% endfor %}
{% endblock %}

{% block script %}
<script>
    function cancel_match(pk, reject) {
        $.ajax({
            url: "{% url 'record:match_cancel' %}",
            method: "POST",
            data: {
                pk: pk,
            }
        }).done(function(){
            // 페이지에서 해당 match를 삭제한다.
            $("#"+pk).remove();
            // 건수를 하나 감소시킨다.
            if (reject) {
                var num = $("#num_rejected").text();
                $("#num_rejected").text(num-1);
            }
            else {
                var num = $("#num_by_me").text();
                $("#num_by_me").text(num-1);
            }
        })
    }

    function accept_match(pk) {
        $.ajax({
            url: "{% url 'record:match_accept' %}",
            method: "POST",
            data: {
                pk: pk,
            }
        }).done(function(){
            // 페이지에서 해당 match를 삭제한다.
            $("#"+pk).remove();
            // 건수를 하나 감소시킨다.
            var num = $("#num_to_me").text();
            $("#num_to_me").text(num-1);
        })
    }

    function reject_match(pk) {
        $.ajax({
            url: "{% url 'record:match_reject' %}",
            method: "POST",
            data: {
                pk: pk,
            }
        }).done(function(){
            // 페이지에서 해당 match를 삭제한다.
            $("#"+pk).remove();
            // 건수를 하나 감소시킨다.
            var num = $("#num_to_me").text();
            $("#num_to_me").text(num-1);
        })
    }

    function resend_match(pk) {
        $.ajax({
            url: "{% url 'record:match_resend' %}",
            method: "POST",
            data: {
                pk: pk,
            }
        }).done(function(){
            // // 페이지에서 해당 match를 삭제한다.
            // $("#"+pk).remove();
            // // 건수를 하나 감소시킨다.
            // var num = $("#num_rejected").text();
            // $("#num_rejected").text(num-1);
            // 편의를 위해서, 상대방의 승인 대기중인 매치를 다시 서버에서 받아올 수 있도록 새로고침 한다.
            location.reload();
        })
    }

</script>
{% endblock %}